name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_CHANGE_ARCH_TO_ARM: 1

concurrency:
  group: "tests-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  brew-test-bot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - run: |
          CHECKOUT_PATH=$(brew --repo "$GITHUB_REPOSITORY")
          echo "CHECKOUT_PATH=$CHECKOUT_PATH" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.CHECKOUT_PATH }}

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          debug: true

      - run: brew test-bot --skip-recursive-dependents
